// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RelaxifyEventRentWeb.DataAccess.Data;

#nullable disable

namespace RelaxifyEventRentWeb.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240113125148_addProductsToDb")]
    partial class addProductsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RelaxifyEventRentWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Namioty"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 1,
                            Name = "Podłoga do namiotów"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 1,
                            Name = "Krzesła"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 1,
                            Name = "Siedziska"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 1,
                            Name = "Stoły"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 1,
                            Name = "Scena"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 1,
                            Name = "Nagłosnienie"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 1,
                            Name = "Światło"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 1,
                            Name = "Kable 230V"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 1,
                            Name = "Kable siłowe"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 1,
                            Name = "Roździelnie"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 1,
                            Name = "Nagrzewnice"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 1,
                            Name = "Meble z palet"
                        });
                });

            modelBuilder.Entity("RelaxifyEventRentWeb.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Czarny namiot o ymiarach 3x6 idealny na wydarzenia plenerowe.",
                            Price = 450,
                            ProductName = "Namiot 3x6"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Czarny namiot o ymiarach 2x2 idealny na wydarzenia plenerowe.",
                            Price = 250,
                            ProductName = "Namiot 2x2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Podesty sceniczne allustage idealne na Twoje wydarzenia",
                            Price = 30,
                            ProductName = "Podesty sceniczne"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Namiot w kształcie gwiazdy, wyglada swietnie na każdym uroczystm wydarzeniu, ale nie tylko",
                            Price = 2760,
                            ProductName = "Namiot gwiazda"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
