// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RelaxifyEventRentWeb.DataAccess.Data;

#nullable disable

namespace RelaxifyEventRentWeb.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240110210619_AddCategoryToDbAndSeedTable")]
    partial class AddCategoryToDbAndSeedTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RelaxifyEventRentWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Namioty"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 1,
                            Name = "Podłoga do namiotów"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 1,
                            Name = "Krzesła"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 1,
                            Name = "Siedziska"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 1,
                            Name = "Stoły"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 1,
                            Name = "Scena"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 1,
                            Name = "Nagłosnienie"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 1,
                            Name = "Światło"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 1,
                            Name = "Kable 230V"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 1,
                            Name = "Kable siłowe"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 1,
                            Name = "Roździelnie"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 1,
                            Name = "Nagrzewnice"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 1,
                            Name = "Meble z palet"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
